language: go

go:
  - "1.11"

install:
 - go get -v -t github.com/tlin20151/go-oidc/...
 - go get golang.org/x/tools/cmd/cover
 - go get github.com/golang/lint/golint

script:
 - ./test

notifications:
  email: false
